name: deploy_staging
on:
  workflow_dispatch:

jobs:
  manual_deploy:
    runs-on: react-html
    steps: 
      - uses: actions/checkout@v2
      - run: npm install
      - run: CI= npm run build
      - run: rm -r /var/www/html/Searchable-Product-Filter/*
      - run: mv build/* /var/www/html/Searchable-Product-Filter/
      - run: cp /var/www/htaccess /var/www/html/Searchable-Product-Filter/.htaccess
        env:
          CI: true
        
